/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PresentationPrimitive.java
 *
 * Created on 9 Δεκ 2011, 2:14:12 πμ
 */
package routing.Presentation;


import java.util.List;
import routing.Structs.FlowStruct.Flow;

/**
 *
 * @author barbarosa
 */
public class PresentationPrimitive extends javax.swing.JFrame {

    /** Creates new form PresentationPrimitive */
    public PresentationPrimitive(List<Flow> Flows) {
        
        initComponents();
        this.setTitle("Presentations");
        PanelDraw PresentationPanel=new PanelDraw(Flows);
        
       PresentFlows FlowsPanel=new PresentFlows(Flows);
        PresentationPanel.setVisible(true);
        FlowsPanel.setVisible(true);
        this.add(PresentationPanel);
        this.add(FlowsPanel);
        pack();        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
