/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmFreq.java
 *
 * Created on Dec 14, 2011, 3:49:14 AM
 */
package routing;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import routing.Enumerators.TableNames;

/**
 *
 * @author barbarosa
 */
public class frmFreq extends javax.swing.JFrame {

    /** Creates new form frmFreq */
    public frmFreq(int AreaID) {
        initComponents();
        FixTable(AreaID);
        //FreqTable.setTableHeader(null);
    }
    
    
    
    private void FixTable(int AreaID){
        DbConnection db=new DbConnection();
        Connection conn=db.Connect();
        int Rows=FreqTable.getModel().getRowCount();
        int Columns=FreqTable.getModel().getColumnCount();
        try {
            ResultSet AreaFreqRs=db.SelectFromDb(TableNames.AreaFrequencies, "WHERE ID="+AreaID, conn);
            while(AreaFreqRs.next()){
                for (int i=0;i<Columns-1;i++){
                 for (int j=0;j<Rows-1;j++){
                  if((Integer)FreqTable.getValueAt(j, i)==AreaFreqRs.getInt("Frequency")) {
                      FreqTable.setValueAt(0, j, i);
                  } 
                   }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmFreq.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FreqTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FreqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {new Integer(40), new Integer(41), new Integer(42), new Integer(43), new Integer(44)},
                {new Integer(45), new Integer(46), new Integer(47), new Integer(48), new Integer(49)},
                {new Integer(50), new Integer(51), new Integer(52), new Integer(53), new Integer(54)},
                {new Integer(55), new Integer(56), new Integer(57), new Integer(58), new Integer(59)},
                {new Integer(60), new Integer(0), new Integer(0), new Integer(0), null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        FreqTable.setTableHeader(null);
        jScrollPane1.setViewportView(FreqTable);
        FreqTable.getColumnModel().getColumn(0).setResizable(false);
        FreqTable.getColumnModel().getColumn(1).setResizable(false);
        FreqTable.getColumnModel().getColumn(2).setResizable(false);
        FreqTable.getColumnModel().getColumn(3).setResizable(false);
        FreqTable.getColumnModel().getColumn(4).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FreqTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
