/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmStart.java
 *
 * Created on 28 Οκτ 2011, 8:00:39 μμ
 */
package routing;

import java.awt.Toolkit;
import routing.Enumerators.TableNames;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import routing.Test.PresentationPrimitive;

/**
 *
 * @author barbarosa
 */
public class frmStart extends javax.swing.JFrame {
//private List SourceList=new ArrayList<Integer>();
//private List DestinationList=new ArrayList<Integer>();
private Map<Integer,Integer> SourceDestinationMap=new HashMap();
    /** Creates new form frmStart */
    public frmStart() {
        initComponents();
        LoadCombo(SourceCombo);
        LoadCombo(DestCombo);
        btnBack.setIcon(new ImageIcon("./Resources/back-icon.png"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void LoadCombo(JComboBox Box){
        Box.removeAllItems();
        DbConnection db=new DbConnection();
    try {
    Connection conn=db.Connect();
    ResultSet rs=db.SelectFromDb(TableNames.Node, "WHERE Area_flag=1", conn);
    while (rs.next()){
        Box.addItem(rs.getInt("ID"));
    }
    if(!conn.isClosed()){
        conn.close();
    }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExecute = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SourceCombo = new javax.swing.JComboBox();
        DestCombo = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommunicationTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Start"); // NOI18N

        btnExecute.setText("Start");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        jLabel1.setText("Source");

        jLabel2.setText("Destination");

        DestCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        CommunicationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SourceID", "DestinationID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CommunicationTable);

        btnBack.setPreferredSize(new java.awt.Dimension(51, 23));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jButton1.setText("Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(SourceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(DestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addGap(6, 6, 6)
                .addComponent(btnExecute))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SourceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExecute, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
              DefaultTableModel model = new DefaultTableModel();
               model=(DefaultTableModel) CommunicationTable.getModel();
               model.insertRow(model.getRowCount(),new Object[]{SourceCombo.getSelectedItem(),DestCombo.getSelectedItem()});
               
               SourceDestinationMap.put((Integer)SourceCombo.getSelectedItem(),(Integer)DestCombo.getSelectedItem());
//               SourceList.add(SourceCombo.getSelectedItem());
//               DestinationList.add(DestCombo.getSelectedItem());         
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
      
    StartCommunication Communication=new StartCommunication(SourceDestinationMap);
    Communication.Start();
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         this.dispose();
         FrmNodes Nodes = new FrmNodes();
         Nodes.setIconImage(Toolkit.getDefaultToolkit().getImage("./Resources/globe.png"));
         Nodes.setTitle("Nodes Table");
         Nodes.setLocationRelativeTo(null);
         Nodes.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PresentationPrimitive pr=new PresentationPrimitive();
        pr.setLocationRelativeTo(this);
        pr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

  
 
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CommunicationTable;
    private javax.swing.JComboBox DestCombo;
    private javax.swing.JComboBox SourceCombo;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
